/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Radiaz 5170411265
 */
public class anggota extends javax.swing.JFrame {
    private Connection koneksi;
    private koneksi db = new koneksi();
    
    public anggota() {
        initComponents();
        Clear_Data();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        E_Kode_Anggota = new javax.swing.JTextField();
        E_Nama_Anggota = new javax.swing.JTextField();
        E_Alamat = new javax.swing.JTextField();
        E_Nomor = new javax.swing.JTextField();
        B_Simpan = new javax.swing.JButton();
        B_Ubah = new javax.swing.JButton();
        B_Hapus = new javax.swing.JButton();
        B_Clear = new javax.swing.JButton();
        R_Perempuan = new javax.swing.JRadioButton();
        R_Laki_Laki = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_Anggota = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(" DATA ANGGOTA");

        jLabel2.setText("Kode Anggota");

        jLabel3.setText("Nama Anggota");

        jLabel4.setText("Alamat");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("No Telephone");

        B_Simpan.setText("SIMPAN");
        B_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SimpanActionPerformed(evt);
            }
        });

        B_Ubah.setText("UBAH");
        B_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_UbahActionPerformed(evt);
            }
        });

        B_Hapus.setText("HAPUS");
        B_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_HapusActionPerformed(evt);
            }
        });

        B_Clear.setText("CLEAR");
        B_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_ClearMouseClicked(evt);
            }
        });

        R_Perempuan.setText("Perempuan");
        R_Perempuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                R_PerempuanMouseClicked(evt);
            }
        });

        R_Laki_Laki.setText("Laki-Laki");
        R_Laki_Laki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                R_Laki_LakiMouseClicked(evt);
            }
        });
    
  
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngJenKel = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        E_Kode_Anggota = new javax.swing.JTextField();
        E_Nama_Anggota = new javax.swing.JTextField();
        E_Alamat = new javax.swing.JTextField();
        E_Nomor = new javax.swing.JTextField();
        R_Laki_Laki = new javax.swing.JRadioButton();
        R_Perempuan = new javax.swing.JRadioButton();
        B_Simpan = new javax.swing.JButton();
        B_Hapus = new javax.swing.JButton();
        B_Ubah = new javax.swing.JButton();
        B_Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_Anggota = new javax.swing.JTable();

        jButton3.setText("UBAH");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATA ANGGOTA");

        jLabel2.setText("Kode Anggota");

        jLabel3.setText("Nama Anggota");

        jLabel4.setText("Alamat");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Nomor Telepon");
        jLabel6.setName("Nomor Telepon"); // NOI18N

        E_Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_AlamatActionPerformed(evt);
            }
        });

        btngJenKel.add(R_Laki_Laki);
        R_Laki_Laki.setText("Laki-Laki");
        R_Laki_Laki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                R_Laki_LakiMouseClicked(evt);
            }
        });

        btngJenKel.add(R_Perempuan);
        R_Perempuan.setText("Perempuan");

        B_Simpan.setText("SIMPAN");
        B_Simpan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                B_SimpanInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                B_SimpanCaretPositionChanged(evt);
            }
        });

        B_Hapus.setText("HAPUS");

        B_Ubah.setText("UBAH");
        B_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_UbahActionPerformed(evt);
            }
        });

        B_Clear.setText("CLEAR");

        T_Anggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        T_Anggota.setName(""); // NOI18N
        jScrollPane1.setViewportView(T_Anggota);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E_Kode_Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_Nama_Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(R_Laki_Laki)
                                .addGap(18, 18, 18)
                                .addComponent(R_Perempuan))
                            .addComponent(E_Nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(B_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(E_Kode_Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(E_Nama_Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(E_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(R_Laki_Laki)
                            .addComponent(R_Perempuan))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(E_Nomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(B_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(B_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        R_Laki_Laki.getAccessibleContext().setAccessibleName("");
        R_Perempuan.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_UbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_UbahActionPerformed

    private void E_AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_AlamatActionPerformed

    private void R_Laki_LakiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R_Laki_LakiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_R_Laki_LakiMouseClicked

    private void B_SimpanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_B_SimpanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_B_SimpanInputMethodTextChanged

    private void B_SimpanCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_B_SimpanCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_B_SimpanCaretPositionChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new anggota().setVisible(true);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }
    
    private void Simpan_Data(){
        try{
            String sql = "INSERT INTO anggota (kode_anggota,nama_anggota,alamat_anggota,jenis_kelamin,no_telp_anggota"
                    + "VALUES (?,?,?,?,?,?";
            PreparedStatemenet ps;
            ps = db.getConnection().prepareStatement(sql);
            ps.setString(1, E_Kode_Anggota.getText());
            ps.setString(1, E_Nama_Anggota.getText());
            ps.setString(1, E_Alamat.getText());
            if(R.Laki_Laki.isSelected()){
                ps.setString(4, "0");
            }else{
                ps.setString(4, "1");
            }
            ps.setString(5, E_Nomor.getText());
            ps.executeUpdate();                        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        Clear_Data();
    }
    
    private void Clear_Data(){
        E_Kode_Anggota.setText("");
        E_Nama_Anggota.setText("");
        E_Alamat.setText("");
        E_Nomor.setText("");
        R_Laki_Laki.setSelected(false);
        R_Perempuan.setSelected(false);
        E_Kode_Anggota.requestFocus();
        Tampil_Data();             
    }
    
    public anggota() {
        intComponents();
        Clear_Data();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Clear;
    private javax.swing.JButton B_Hapus;
    private javax.swing.JButton B_Simpan;
    private javax.swing.JButton B_Ubah;
    private javax.swing.JTextField E_Alamat;
    private javax.swing.JTextField E_Kode_Anggota;
    private javax.swing.JTextField E_Nama_Anggota;
    private javax.swing.JTextField E_Nomor;
    private javax.swing.JRadioButton R_Laki_Laki;
    private javax.swing.JRadioButton R_Perempuan;
    private javax.swing.JTable T_Anggota;
    private javax.swing.ButtonGroup btngJenKel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void intComponents() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
